# Server
server.port=${PORT:8080}

# PostgreSQL datasourcepsql 'postgresql://neondb_owner:npg_kLSWhlcFH50i@ep-dark-math-aqtl14sh-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ep-dark-math-aqtl14sh-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'
spring.datasource.username=neondb_owner
spring.datasource.password=npg_kLSWhlcFH50i

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Validation
spring.mvc.throw-exception-if-no-handler-found=true

# App name
spring.application.name=portfolio-backend